<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ /*
  ~  * (c) 2025 Nils Kevin Koerting-Eberhardt (realEntwickler)
  ~  *
  ~  * File: pom.xml
  ~  * Created on: 23.10.25, 13:44
  ~  *
  ~  * This file is part of the project "smayl-backend".
  ~  *
  ~  * Licensed under the Creative Commons Attribution - NonCommercial -
  ~  * NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
  ~  *
  ~  * For more information about this license, please visit:
  ~  * https://creativecommons.org/licenses/by-nc-nd/4.0/
  ~  */
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>rlp.hoev.smayl</groupId>
    <artifactId>backend</artifactId>
    <version>2.0.1-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>rlp.hoev.smayl.backend.launcher.SmaylBackendLauncher</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>