#
# /*
#  * (c) 2025 Nils Kevin Koerting-Eberhardt (realEntwickler)
#  *
#  * File: application.properties
#  * Created on: 25.10.25, 09:20
#  *
#  * This file is part of the project "smayl-backend".
#  *
#  * Licensed under the Creative Commons Attribution - NonCommercial -
#  * NoDerivatives 4.0 International License (CC BY-NC-ND 4.0).
#  *
#  * For more information about this license, please visit:
#  * https://creativecommons.org/licenses/by-nc-nd/4.0/
#  */
#
spring.mongodb.host=172.16.1.18
spring.mongodb.database=smayl
spring.mongodb.authentication-database=smayl
spring.mongodb.password=IrPA^F4w0LSbE8OAK^Qm%ERb$xTt!KN6llUIjA$1
spring.mongodb.port=28018
spring.mongodb.username=smaylbackend